name: Pokémon App CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  

    - name: Restore dependencies
      run: dotnet restore src/pokemon_test.sln

    - name: Build
      run: dotnet build src/pokemon_test.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test src/pokemon_test.sln --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish src/pokemon_test.sln --configuration Release --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pokemon-app
        path: ./publish
